---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - sharedresources.developer.redhat.com.developer.redhat.com
  resources:
  - configs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sharedresources.developer.redhat.com.developer.redhat.com
  resources:
  - configs/finalizers
  verbs:
  - update
- apiGroups:
  - sharedresources.developer.redhat.com.developer.redhat.com
  resources:
  - configs/status
  verbs:
  - get
  - patch
  - update
