apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: shared-resource-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Config is the Schema for the configs API
      displayName: Config
      kind: Config
      name: configs.sharedresources.developer.redhat.com.developer.redhat.com
      version: v1
  description: This operator is the generally available and fully supported version
    of the Shared Resources CSI Driver Operator originally provided as a Technology
    Preview feature within OpenShift Container Platform.
  displayName: Red Hat Developer Shared Resource Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - shared-resources
  - shared-secrets
  - shared-configmap
  links:
  - name: Shared Resource Operator
    url: https://shared-resource-operator.domain
  maturity: alpha
  provider:
    name: Shared Resource Operator
  version: 0.0.0
