apiVersion: sharedresources.developer.redhat.com.developer.redhat.com/v1
kind: Config
metadata:
  labels:
    app.kubernetes.io/name: config
    app.kubernetes.io/instance: config-sample
    app.kubernetes.io/part-of: shared-resource-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: shared-resource-operator
  name: config-sample
spec:
  # TODO(user): Add fields here
