---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: shared-resource-csi-driver-pdb
  namespace: shared-resource-csi-driver
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      name: shared-resource-csi-driver-webhook

